# Generated by Django 4.1.7 on 2023-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='User'),
        ),
    ]
