# Generated by Django 4.1.7 on 2023-02-22 03:32

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0004_alter_netflixuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('biography', models.TextField()),
                ('image', models.FileField(max_length=600, upload_to='cast')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('episode_no', models.IntegerField(default=0)),
                ('episode_url', models.URLField(max_length=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('Series', 'Series')], default='movie', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('media_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255), unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField(default=datetime.datetime(2023, 2, 22, 3, 32, 54, 579716, tzinfo=datetime.timezone.utc))),
                ('poster', models.FileField(max_length=600, upload_to='media/poster')),
                ('media_video', models.URLField(blank=True, max_length=600, null=True)),
                ('is_season', models.BooleanField(default=False)),
                ('cast', models.ManyToManyField(to='netflix_backend_api.cast')),
                ('genres', models.ManyToManyField(to='netflix_backend_api.genres')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer', models.URLField(max_length=600)),
                ('thumbnail', models.FileField(max_length=600, upload_to='media/thumbnail')),
                ('release_date', models.DateField(default=datetime.datetime(2023, 2, 22, 3, 32, 54, 579716, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('bengali', 'Bengali')], default='english', max_length=255, verbose_name='Prefered Language')),
                ('profile_picture', models.FileField(max_length=600, upload_to='user/profile', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('season_no', models.IntegerField(default=0)),
                ('season_poster', models.FileField(max_length=600, upload_to='media/season-poster')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='media',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.season'),
        ),
        migrations.AddField(
            model_name='media',
            name='trailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.trailer'),
        ),
    ]
