# Generated by Django 4.1.7 on 2023-02-22 04:04

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0005_cast_episode_genres_media_trailer_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=models.CharField(max_length=255), unique=True),
        ),
        migrations.AddField(
            model_name='season',
            name='season_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=models.CharField(max_length=255), unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 4, 4, 36, 576309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 4, 4, 36, 576309, tzinfo=datetime.timezone.utc)),
        ),
    ]
