# Generated by Django 4.1.7 on 2023-02-22 04:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0007_remove_season_episode_episode_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='trailer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.trailer'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='trailer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 4, 54, 10, 596280, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 4, 54, 10, 596280, tzinfo=datetime.timezone.utc)),
        ),
    ]
