# Generated by Django 4.1.7 on 2023-02-22 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0008_season_trailer_trailer_trailer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Media Casts'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Media Genre'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media-Movies/Seasons'},
        ),
        migrations.AlterModelOptions(
            name='netflixuser',
            options={'verbose_name_plural': 'Netflix User Profile'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'User Review'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name_plural': 'Media Trailer'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name_plural': 'User Watchlist'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.season'),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 5, 39, 9, 399157, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 5, 39, 9, 399157, tzinfo=datetime.timezone.utc)),
        ),
    ]
