# Generated by Django 4.1.7 on 2023-02-22 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0010_alter_media_release_date_alter_trailer_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='trailer',
            new_name='trailer_url',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('reset_password', 'Reset Password')], default='email_verification', max_length=255),
        ),
        migrations.AlterField(
            model_name='cast',
            name='image',
            field=models.FileField(max_length=600, upload_to='cast/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.FileField(max_length=600, upload_to='media/poster/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 6, 41, 49, 99853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_poster',
            field=models.FileField(max_length=600, upload_to='media/season-poster/'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 6, 41, 49, 99853, tzinfo=datetime.timezone.utc)),
        ),
    ]
