# Generated by Django 4.1.7 on 2023-02-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0013_alter_episode_description_alter_media_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 8, 54, 38, 901759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 8, 54, 38, 901759, tzinfo=datetime.timezone.utc)),
        ),
    ]
