# Generated by Django 4.1.7 on 2023-02-22 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0014_alter_media_release_date_alter_trailer_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 10, 53, 30, 182659, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 10, 53, 30, 182659, tzinfo=datetime.timezone.utc)),
        ),
    ]
