# Generated by Django 4.1.7 on 2023-02-22 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0015_alter_media_release_date_alter_trailer_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='140849', max_length=255),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
