# Generated by Django 4.1.7 on 2023-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0017_alter_otp_otp_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='298379', max_length=255),
        ),
    ]
