# Generated by Django 4.1.7 on 2023-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0018_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
