# Generated by Django 4.1.7 on 2023-02-23 15:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0020_alter_otp_otp_alter_otp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('movie_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255), unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('poster', models.FileField(max_length=600, upload_to='movie/poster/')),
                ('movie_video', models.URLField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.RemoveField(
            model_name='media',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='media',
            name='season',
        ),
        migrations.RemoveField(
            model_name='media',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='season',
            name='trailer',
        ),
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Movie Casts'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Movie Genre'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name_plural': 'Movie Trailer'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='media',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='trailer_name',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='media',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='thumbnail',
            field=models.FileField(max_length=600, upload_to='movie/thumbnail'),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='netflix_backend_api.genres'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='netflix_backend_api.movie'),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.movie'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='movie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_backend_api.movie'),
        ),
    ]
