# Generated by Django 4.1.7 on 2023-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0021_movie_remove_media_cast_remove_media_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(to='netflix_backend_api.movie'),
        ),
    ]
