# Generated by Django 4.1.7 on 2023-02-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0024_rename_movie_video_movie_movie_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='thumbnail',
        ),
    ]
