# Generated by Django 4.1.7 on 2023-02-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_backend_api', '0025_remove_trailer_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('bengali', 'Bengali')], default='english', max_length=255),
        ),
    ]
